### ISSUE TITLE
Concourse 5.0 Docs todo

### ISSUE THREAD

**Issue by jama22** [concourse/docs#143]
Here's a short list of Concourse 5.0 Documentation TODOs pre-release:

- Release Notes
- [x] RBAC
     - [x] Installing
     - [x] `set-team`
     - [x] RBAC Matrix 
- [ ] Global Resource
     - [ ] Concepts
     - [ ] BOSH.io docs
- [x] Container Placement Strategy
- [x] Task Params / Vars
- [x] Resource Pinning
     - [x] Fly
     - [x] Pause version Removal

**Comment by jama22** [comment]
PR for container placement strategy in-flight https://github.com/concourse/docs/pull/148
